'use client';

import { useState, useEffect } from 'react';
import { useSession } from 'next-auth/react';
import { ChatInterface } from '@/components/chat-interface';
import { ChatSidebar } from '@/components/chat-sidebar';
import { useChatStore } from '@/store/chat.store';
import type { ChatSession } from '@/types/chat.types';

import { useSearchParams, useRouter } from 'next/navigation';
import { useNotificationStore } from '@/store/notification.store';

export default function HomePage() {
    const [chatKey, setChatKey] = useState(0);
    const { addSession, currentSessionId, loadSessions } = useChatStore();
    const searchParams = useSearchParams();
    const router = useRouter();
    const { addNotification } = useNotificationStore();

    // Handle Login Success Notification
    useEffect(() => {
        if (searchParams.get('login') === 'success') {
            addNotification({
                type: 'success',
                message: 'Đăng nhập thành công! Chào mừng bạn quay lại.',
            });
            // Clean up the URL parameter
            router.replace('/');
        }
    }, [searchParams, addNotification, router]);

    const { data: sessionData, status } = useSession();

    // Load sessions from API on mount
    useEffect(() => {
        // Clear old localStorage data from before database migration
        if (typeof window !== 'undefined') {
            localStorage.removeItem('chat-storage');
        }

        if (status === 'authenticated' && sessionData?.user) {
            loadSessions();
        } else if (status === 'unauthenticated') {
            useChatStore.getState().clearAllSessions();
        }
    }, [status, sessionData, loadSessions]);

    const handleNewChat = async () => {
        // Guest Mode: Just reset the UI state without saving to DB
        if (!sessionData?.user) {
            setChatKey((prev) => prev + 1);
            return;
        }

        // Generate unique title with timestamp
        const timeStr = new Date().toLocaleTimeString('vi-VN', {
            hour: '2-digit',
            minute: '2-digit'
        });

        const newSession: ChatSession = {
            id: '', // Will be generated by database
            title: `Chat mới (${timeStr})`,
            messages: [],
            model: 'deepseek-r1:8b',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        };

        const createdSession = await addSession(newSession);
        if (createdSession) {
            setChatKey((prev) => prev + 1); // Force re-render ChatInterface
        }
    };

    return (
        <div className="flex flex-col h-dvh overflow-hidden bg-background">
            <div className="flex flex-1 relative overflow-hidden">
                <ChatSidebar onNewChat={handleNewChat} />
                <div className="flex-1 overflow-hidden h-full">
                    <ChatInterface key={chatKey} sessionId={currentSessionId} />
                </div>
            </div>
        </div>
    );
}
